/** Public deterministic CIP-8 TEST vectors. No wallet capture or chain input. */
import { writeFileSync } from 'node:fs';
import { fixtureAddress, fixturePublicKey, signFixture } from '../tests/fixtures.js';
import { decodeCbor, encodeCbor, fromHex, toHex, verifyCip8Signature, type Cbor } from '../packages/wallet/src/index.js';

const records: any[] = [];
for (const type of [0, 2, 6, 14] as const) for (const includeKid of [false, true]) {
  const address = fixtureAddress(type);
  for (const purpose of ['enrollment', 'operation']) {
    const payload = purpose === 'enrollment' ? new TextEncoder().encode('cardano-kernel:generated-cip8-enrollment:v1:' + 'x'.repeat(96)) : new Uint8Array(32).fill(0x42);
    const signed = signFixture(payload, address, undefined, includeKid);
    const id = `${type}-${includeKid ? 'kid' : 'no-kid'}-${purpose}`;
    const expected = { address: toHex(address), network: 0 as const, payload };
    verifyCip8Signature(signed, expected);
    const base = { id, type, credential: type === 14 ? 'stake' : 'payment', includeKid, purpose, address: toHex(address), network: 0, payload: toHex(payload), publicKey: toHex(fixturePublicKey), signed };
    records.push({ ...base, accepted: true, hashed: false });
    if (purpose !== 'operation') continue;
    const decode = () => decodeCbor(fromHex(signed.signature)) as Cbor[];
    const hashed = decode(); hashed[1] = new Map([['hashed', true]]);
    const truncated = decode(); truncated[3] = (truncated[3] as Uint8Array).slice(0, 63);
    const badHeader = decode();
    const headers = decodeCbor(badHeader[0] as Uint8Array) as Map<string | number, Cbor>;
    headers.set('unsupported', true); badHeader[0] = encodeCbor(headers);
    for (const [name, sign1, error] of [['hashed', hashed, 'hashed payload'], ['signature-length', truncated, 'signature length'], ['protected-header', badHeader, 'Unsupported COSE header']] as const) {
      const malformed = { ...signed, signature: toHex(encodeCbor(sign1)) };
      let rejected = false;
      try { verifyCip8Signature(malformed, expected); } catch (failure) { if (!(failure instanceof Error) || !failure.message.includes(error)) throw failure; rejected = true; }
      if (!rejected) throw new Error('Malformed test vector was accepted');
      records.push({ ...base, id: `${id}-${name}`, signed: malformed, accepted: false, error, hashed: name === 'hashed' });
    }
  }
}
writeFileSync('fixtures/wallet-signatures.json', JSON.stringify({ kind: 'generated-public-cip8-test-data', testData: true, realWallet: false, provenance: 'Generated by scripts/export-wallet-fixtures.ts using the public test seed and signing helpers in tests/fixtures.ts. Hashed payloads are rejection controls.', records }, null, 2) + '\n');
console.log(JSON.stringify({ generatedWalletSignatures: records.length, accepted: records.filter(r => r.accepted).length, rejected: records.filter(r => !r.accepted).length }));
